# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='tag',
            field=models.ForeignKey(default=1, help_text='Select any given tag for reference', on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
