# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180206_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='tag',
            field=models.ForeignKey(choices=[('Furniture_issue', 'Furniture_issue'), ('Electricity_issue', 'Electricity_issue'), ('Water_issue', 'Water_issue')], default='1', help_text='Select any given tag for reference', on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
