# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180206_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='tag',
            field=models.CharField(default=None, help_text='Select any given tag for reference', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
